Remove gcc-4.5 compilation errors: external/dbus/dbus/dbus-transport.c: In function '_dbus_transport_open': external/dbus/dbus/dbus-transport.c:356:7: error: the comparison will always evaluate as 'false' for the address of 'tmp_error' will never be NULL [-Werror=address]
The key problem is that the macro _DBUS_ASSERT_ERROR_IS_CLEAR
and _DBUS_ASSERT_ERROR_IS_SET try to first check if &tmp_error==NULL.
gcc-4.5 reports an error, if tmp_error is a local stack variable
since &tmp_error will never be NULL.
gcc-4.4 and earlier versions are not as strict as gcc-4.5. We start
to see this type of errors from gcc-4.5.

This patch simply remove the "&tmp_error==NULL" comparisons only if
tmp_error is a local stack variable without changing anything else.
There may be better changes. But this patch is very consertative.
It keeps original comparison orders without making any assumption.

Change-Id: Ib16a6482765247f25ac6458e06861b077ed88ed5